# Copyright (c) 2026, QuACK team.

"""SM120 direct rank-2 TMA helpers.

These helpers wrap a local CuTe DSL workaround for SM120 rank-2 G2S TMA.  They
are intentionally narrow: dense row-major tensors, explicit TMA basis, and
CTA-local loads only.  Do not use this as a generic replacement for
``cute.copy``-based TMA.
"""

from __future__ import annotations

import torch

import cutlass
import cutlass.cute as cute
from cutlass import const_expr
from cutlass.cute.nvgpu import cpasync
from cutlass.cutlass_dsl import dsl_user_op

from quack.cute_dsl_utils import get_device_capacity


_REQUIRED_CPASYNC_HELPERS = (
    "get_tma_desc_addr",
    "make_sm120_tma_load_2d_atom",
    "sm120_tma_load_2d",
)


def has_sm120_direct_tma_2d(device=None, require_device: bool = False) -> bool:
    """Return whether the local environment can use the SM120 direct 2D TMA path."""
    if not all(hasattr(cpasync, name) for name in _REQUIRED_CPASYNC_HELPERS):
        return False
    if require_device:
        if not torch.cuda.is_available():
            return False
        return get_device_capacity(device)[0] == 12
    return True


def assert_sm120_direct_tma_2d(device=None, require_device: bool = True) -> None:
    """Raise a clear error if the SM120 direct 2D TMA workaround is unavailable."""
    missing = [name for name in _REQUIRED_CPASYNC_HELPERS if not hasattr(cpasync, name)]
    if missing:
        missing_s = ", ".join(missing)
        raise RuntimeError(
            "SM120 direct rank-2 TMA requires the local CuTe DSL workaround helpers "
            f"({missing_s} missing). Use the CUTLASS branch that provides "
            "cpasync.make_sm120_tma_load_2d_atom and cpasync.sm120_tma_load_2d."
        )
    if require_device:
        if not torch.cuda.is_available():
            raise RuntimeError("SM120 direct rank-2 TMA requires CUDA")
        capability = get_device_capacity(device)
        if capability[0] != 12:
            raise RuntimeError(
                "SM120 direct rank-2 TMA is only supported on compute capability 12.x; "
                f"got {capability}"
            )


@dsl_user_op
def make_sm120_tma_basis_tensor_2d(
    gmem_tensor: cute.Tensor,
    d_total: cutlass.Constexpr[int],
    seq_total: cutlass.Constexpr[int],
    *,
    loc=None,
    ip=None,
) -> cute.Tensor:
    """Create the explicit SM120 TMA-basis view for row-major logical ``[seq, d]``.

    The resulting tensor has shape ``(d_total, seq_total)`` and stride
    ``(1, d_total)``.  SM120 direct TMA coordinates are therefore
    ``(d_coord, seq_coord)``.
    """
    return cute.make_tensor(
        gmem_tensor.iterator,
        cute.make_layout((d_total, seq_total), stride=(1, d_total)),
        loc=loc,
        ip=ip,
    )


@dsl_user_op
def make_sm120_direct_tma_smem_layout_2d(
    d_tile: cutlass.Constexpr[int],
    seq_tile: cutlass.Constexpr[int],
    *,
    swizzle: cutlass.Constexpr[bool] = False,
    loc=None,
    ip=None,
) -> cute.Layout | cute.ComposedLayout:
    """Create the SMEM layout used by the SM120 direct rank-2 TMA path.

    The base layout is the explicit TMA basis ``(d, seq)`` with stride
    ``(1, d_tile)``.  When ``swizzle`` is true, the returned layout is the
    conservative SW128-style composed layout validated by the local CuTe DSL
    direct-TMA smoke test.  The TMA atom layout and destination SMEM pointer
    must use the same swizzle.
    """
    smem_layout = cute.make_layout((d_tile, seq_tile), stride=(1, d_tile))
    if const_expr(swizzle):
        return cute.make_composed_layout(
            cute.make_swizzle(3, 4, 3),
            0,
            smem_layout,
        )
    return smem_layout


@dsl_user_op
def make_sm120_direct_tma_load_2d_atom(
    gmem_tma_tensor: cute.Tensor,
    smem_layout: cute.Layout | cute.ComposedLayout,
    cta_tiler: cute.Tile,
    *,
    internal_type: cutlass.Constexpr = None,
    loc=None,
    ip=None,
):
    """Build a CuTe descriptor for the direct SM120 rank-2 TMA load path."""
    assert const_expr(hasattr(cpasync, "make_sm120_tma_load_2d_atom")), (
        "cpasync.make_sm120_tma_load_2d_atom is unavailable; use the local CuTe DSL "
        "SM120 direct TMA branch"
    )
    return cpasync.make_sm120_tma_load_2d_atom(
        gmem_tma_tensor,
        smem_layout,
        cta_tiler,
        internal_type=internal_type,
        loc=loc,
        ip=ip,
    )


@dsl_user_op
def get_sm120_direct_tma_desc_addr(tma_atom: cute.CopyAtom, *, loc=None, ip=None) -> cute.Pointer:
    """Return the descriptor pointer generated by the SM120 direct TMA atom."""
    assert const_expr(hasattr(cpasync, "get_tma_desc_addr")), (
        "cpasync.get_tma_desc_addr is unavailable; use the local CuTe DSL SM120 direct TMA branch"
    )
    return cpasync.get_tma_desc_addr(tma_atom, loc=loc, ip=ip)


@dsl_user_op
def sm120_direct_tma_load_2d(
    dst_smem_ptr: cute.Pointer,
    tma_desc_ptr: cute.Pointer,
    tma_bar_ptr: cute.Pointer,
    coord0: cutlass.Int32,
    coord1: cutlass.Int32,
    *,
    cache_policy: cutlass.Int64 | None = None,
    already_elected: cutlass.Constexpr[bool] = False,
    tile_mode: cutlass.Constexpr[bool] = False,
    loc=None,
    ip=None,
) -> None:
    """Issue one CTA-local SM120 direct-basis rank-2 G2S TMA transaction."""
    assert const_expr(hasattr(cpasync, "sm120_tma_load_2d")), (
        "cpasync.sm120_tma_load_2d is unavailable; use the local CuTe DSL SM120 direct TMA branch"
    )
    cpasync.sm120_tma_load_2d(
        dst_smem_ptr,
        tma_desc_ptr,
        tma_bar_ptr,
        coord0,
        coord1,
        cache_policy=cache_policy,
        already_elected=already_elected,
        tile_mode=tile_mode,
        loc=loc,
        ip=ip,
    )
