repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^quack/.*\.py$
      # - id: ruff-format
      #   files: ^quack/.*\.py$
