repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
        files: ^(quack|tests)/.*\.py$
      # - id: ruff-format
      #   files: ^(quack|tests)/.*\.py$
